version: "1.0.{build}"
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - main
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore src/shpero-sdk.sln --verbosity q
build_script:
  - cmd: dotnet build src/shpero-sdk.sln -c Release
after_build:
  # For once the build has completed
  - cmd: dotnet pack src/shpero-sdk.sln -o packages -c Release
artifacts:
  - path: "packages/**/*.nupkg"
    name: NugetPackages

clone_depth: 1
test_script:
    - cmd: dotnet test src/shpero-sdk.sln
deploy:
  - provider: NuGet
    api_key:
      secure: XwA+GEOxVj/7tZ8Z0GPBLa23lZlrFPRezTWQ3KwjCV+Q87uakfOP8H29sNPJmB7T

    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
    on:
      branch: main
